#!/bin/bash

if [ "$#" -eq 0 ]; then
  echo "Usage: $0 <Filename>"
  exit
fi

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
java -cp "$DIR/out/production/Assembler" com.theKidOfArcrania.re2.RESquaredAssembler $1
